# Generated by Django 4.2.7 on 2024-01-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='image',
            field=models.ImageField(upload_to='editor/images/'),
        ),
    ]
