# Generated by Django 4.2.7 on 2024-01-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0002_alter_editor_image'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('publishing_time', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.editor')),
            ],
        ),
    ]
